import react, { Component } from 'react'
import JokeCategorySelector from './JokeCategorySelector'
import JokeParagraph from './JokeParagraph'
class JokeDisplay extends Component {
	
	constructor () {
		super ()
		/* Properties needed:
			showJoke: boolean variable | used to determinete visibility of child component
			selectedCategory: stores pre-selected category value
			category: stores selected category value
			jokeData: stores joke date generated by external API
		*/
		this.state = {
			showJoke: false,
			selectedCategory: 'random',
			category: '',
			jokeData: ''
		}
	}
	
	// onClick fuction used in 'Generate Joke' button
	onClick = (event) => {
		// set ShowJoke to true, so component becomes visible
		this.setState({showJoke: true})
		this.setState({
			category: this.state.selectedCategory
		})
		// retrieve joke
		this.getJoke()
	}

	// Function to retrieve joke from API
	async getJoke ()  {
		// endpoint wihtout category
		let apiURL = "https://api.chucknorris.io/jokes/random"
		// if category is not random, edit endpoint to add category
		if (this.state.selectedCategory !== 'random') {
			apiURL = `https://api.chucknorris.io/jokes/random?category=${this.state.selectedCategory}`
		}
		let response = await fetch(apiURL)
		let jokeData = await response.json()
		this.setState({
			jokeData: jokeData.value
		})
	}
	// Fucntion to update selected Category
	changeCategory = (value) => {
		this.setState({
			selectedCategory: value
		})
	}
	render () {
		return (
			<div className="row">
				<div className="col-md-7 col-lg-6 mt-5 text-center text-md-start">
					<h1 className="fw-medium">
						It's time to laugh<br></br>a lot with 
						<span class="fw-bold">Polpo Joke.</span>
					</h1>
					<p className="mt-3 mb-4">
						We provide an infinite ammount of jokes so you can always laugh and smile, with 
						<span className="fw-medium"> <strong>Polpo Joke </strong></span>
						discover funny jokes from 
						<a href=" https://api.chucknorris.io/"> https://api.chucknorris.io/</a>
					</p>
					{/* Joke category selector component, parameters: changeCategory */}
					<JokeCategorySelector onChange={data => this.changeCategory(data)}/>
					<a onClick={this.onClick} 
						className="btn btn-lg mt-5 btn-danger hover-top btn-glow" href="#">Generate Joke</a>
				</div>
				<div className="col-md-5 mt-5 text-center text-md-start">
					<div id="jokeDiv">
						{
							// show or hide componet
							this.state.showJoke ?
								<JokeParagraph category={this.state.category} jokeData ={this.state.jokeData}/>
								: null

						}
					</div>
				</div>	
			</div>
		)
	}
}

export default JokeDisplay